application: codesville
version: 3-test
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webob
  version: "1.1.1"
- name: webapp2
  version: "2.5.2"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
